### ISSUE TITLE
Copy of safeguard.js and safeguardJsAccessTokenChecker.js in sample folders may lead to out of date files

### ISSUE THREAD

**Issue by LeeHoward1** [OneIdentity/safeguard.js#3]
I noticed that there are full copies of safeguard.js and safeguardJsAccessTokenChecker.js in the sample folders. This may not be a problem, but I thought I'd bring up the possibility that those files might be out of date if people forget to update them when updating the main copies of the files.

**Comment by RichGagliano** [comment]
I had this same concern when I added the files to the samples. I ran into an issue with my web server hosting the samples in that I could not reference a file above my root index.html file. 

If there is a way to accomplish that reference that would be great and we can remove these duplicates.

**Comment by RichGagliano** [comment]
Copying the web .js files to the sample directories has been bundled with the minification process and automated as part of 'npm run build'. PR: #5
