### ISSUE TITLE
No 2FA support

### ISSUE THREAD

**Issue by LeeHoward1** [OneIdentity/safeguard.js#4]
As I was looking through safeguard.js and safeguardJsAccessTokenChecker.js, I didn't see anything that would suggest the 2FA workflow is supported. When the user token comes back from the Safeguard, if the 'Status' flag has a value of 'Needs2FA', the code needs to redirect back to the RSTS to handle the 2FA portion of authentication.

**Comment by RichGagliano** [comment]
(Edited) I did some testing and 2FA is currently supported using at least a 6.0.0 or later Safeguard appliance. Earlier version of Safeguard may not be supported for 2FA as I'm unsure of the exact version where we switched from the redirect method you mentioned above. Including support for 2FA in these earlier builds in safeguard.js will be discussed for a future release.

**Comment by RichGagliano** [comment]
Decision was made that 2FA will currently only be supported for interactive login via RSTS when targeting a Safeguard appliance that is version 6.0.0 or later.
